import type { ResearchPaper } from "@/lib/types";

export const researchPapers: ResearchPaper[] = [
  {
    slug: "nvda-supply-chain-reacceleration",
    title: "NVDA Supply Chain Reacceleration",
    subtitle: "Channel checks point to renewed accelerator backlog strength.",
    abstract:
      "Taiwan substrate lead times, hyperscaler capex revisions, and export-control scenario work support a constructive read-through for AI infrastructure leaders into the next two quarters.",
    category: "Signal Report",
    authors: [
      { name: "Maya Iyer", role: "Lead Semiconductor Analyst", desk: "Equity Research" },
      { name: "Leo Tran", role: "Model Risk Associate", desk: "AI Signals" },
    ],
    publishedAt: "2026-05-27T13:30:00Z",
    updatedAt: "2026-05-29T08:15:00Z",
    tickers: ["NVDA", "TSM", "AVGO"],
    tags: ["semis", "ai-capex", "supply-chain", "momentum"],
    readingMinutes: 8,
    confidence: 0.88,
    signalDirection: "buy",
    horizon: "swing",
    dataFreshness: "live",
  },
  {
    slug: "crude-volatility-opec-policy-band",
    title: "Crude Volatility Inside the OPEC Policy Band",
    subtitle: "Inventory draws are not yet strong enough to break the range.",
    abstract:
      "The desk model sees higher realized volatility but only modest directional edge as refinery runs, floating storage, and policy rhetoric keep WTI balanced near the upper half of its range.",
    category: "Market Brief",
    authors: [
      { name: "Jon Bell", role: "Macro Commodities Strategist", desk: "Global Macro" },
    ],
    publishedAt: "2026-05-24T10:00:00Z",
    updatedAt: "2026-05-28T19:40:00Z",
    tickers: ["CL", "XLE", "OXY"],
    tags: ["energy", "macro", "volatility", "inventory"],
    readingMinutes: 6,
    confidence: 0.72,
    signalDirection: "hold",
    horizon: "position",
    dataFreshness: "delayed",
  },
  {
    slug: "jpm-credit-card-delinquency-watch",
    title: "JPM Credit Card Delinquency Watch",
    subtitle: "Prime consumer credit remains orderly but spread upside is capped.",
    abstract:
      "Card charge-off normalization, deposit beta stability, and reserve build sensitivity keep the bank book defensive while limiting near-term upside without a sharper yield curve steepener.",
    category: "Risk Review",
    authors: [
      { name: "Nora Feld", role: "Financials Analyst", desk: "Equity Research" },
      { name: "Samir Patel", role: "Credit Risk Lead", desk: "Risk" },
    ],
    publishedAt: "2026-05-22T14:10:00Z",
    updatedAt: "2026-05-27T21:05:00Z",
    tickers: ["JPM", "BAC", "XLF"],
    tags: ["banks", "credit", "consumer", "risk"],
    readingMinutes: 7,
    confidence: 0.79,
    signalDirection: "hold",
    horizon: "strategic",
    dataFreshness: "live",
  },
  {
    slug: "tesla-delivery-elasticity-refresh",
    title: "Tesla Delivery Elasticity Refresh",
    subtitle: "Price cuts are stabilizing unit velocity but pressuring quality of earnings.",
    abstract:
      "Regional registration data and incentive tracking suggest improving delivery elasticity, though warranty accruals and residual value pressure leave the risk-reward asymmetric.",
    category: "Research Note",
    authors: [
      { name: "Elena Graves", role: "Autos Analyst", desk: "Equity Research" },
    ],
    publishedAt: "2026-05-21T16:45:00Z",
    updatedAt: "2026-05-28T11:20:00Z",
    tickers: ["TSLA", "RIVN", "LCID"],
    tags: ["autos", "ev", "margin", "consumer"],
    readingMinutes: 9,
    confidence: 0.68,
    signalDirection: "sell",
    horizon: "position",
    dataFreshness: "delayed",
  },
  {
    slug: "spy-breadth-thrust-decomposition",
    title: "SPY Breadth Thrust Decomposition",
    subtitle: "Participation is improving outside mega-cap leadership.",
    abstract:
      "Cross-sectional breadth, sector rotation, and options dealer gamma indicate a healthier index tape, but the model flags reduced payoff after the latest volatility compression.",
    category: "Model Memo",
    authors: [
      { name: "Rachel Kim", role: "Quant Researcher", desk: "Systematic Strategies" },
      { name: "Owen Cross", role: "Execution Analyst", desk: "Trading" },
    ],
    publishedAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-05-29T05:55:00Z",
    tickers: ["SPY", "QQQ", "IWM"],
    tags: ["breadth", "index", "options", "momentum"],
    readingMinutes: 5,
    confidence: 0.81,
    signalDirection: "buy",
    horizon: "intraday",
    dataFreshness: "live",
  },
  {
    slug: "msft-copilot-seat-expansion",
    title: "MSFT Copilot Seat Expansion",
    subtitle: "Enterprise attach rates remain the cleanest AI software datapoint.",
    abstract:
      "Procurement checks, Azure workload telemetry, and partner pipeline data support durable Copilot expansion, although valuation requires sustained evidence of gross margin resilience.",
    category: "Signal Report",
    authors: [
      { name: "Maya Iyer", role: "Lead Semiconductor Analyst", desk: "Equity Research" },
      { name: "Priya Shah", role: "Software Strategist", desk: "Equity Research" },
    ],
    publishedAt: "2026-05-19T15:25:00Z",
    updatedAt: "2026-05-26T18:35:00Z",
    tickers: ["MSFT", "ORCL", "CRM"],
    tags: ["software", "ai-capex", "cloud", "enterprise"],
    readingMinutes: 10,
    confidence: 0.84,
    signalDirection: "buy",
    horizon: "strategic",
    dataFreshness: "live",
  },
  {
    slug: "gold-real-yield-stress-map",
    title: "Gold Real Yield Stress Map",
    subtitle: "The hedge still works, but entry discipline matters.",
    abstract:
      "Real yield beta, central bank purchase estimates, and dollar liquidity stress show gold retaining portfolio hedge value while short-term positioning screens warn against chasing breakouts.",
    category: "Market Brief",
    authors: [
      { name: "Jon Bell", role: "Macro Commodities Strategist", desk: "Global Macro" },
      { name: "Kara Voss", role: "Portfolio Risk Analyst", desk: "Risk" },
    ],
    publishedAt: "2026-05-17T09:35:00Z",
    updatedAt: "2026-05-25T16:10:00Z",
    tickers: ["GC", "GLD", "GDX"],
    tags: ["commodities", "rates", "hedge", "macro"],
    readingMinutes: 6,
    confidence: 0.76,
    signalDirection: "hold",
    horizon: "swing",
    dataFreshness: "backtest",
  },
  {
    slug: "coin-liquidity-fragility-note",
    title: "COIN Liquidity Fragility Note",
    subtitle: "Crypto beta is improving, but market depth remains uneven.",
    abstract:
      "Exchange order book depth, ETF flow concentration, and stablecoin settlement activity argue for tactical exposure only until liquidity recovers across venues.",
    category: "Research Note",
    authors: [
      { name: "Miles Chen", role: "Digital Assets Analyst", desk: "Alternatives" },
    ],
    publishedAt: "2026-05-15T18:00:00Z",
    updatedAt: "2026-05-23T22:50:00Z",
    tickers: ["COIN", "BTC", "ETH"],
    tags: ["crypto", "liquidity", "flows", "risk"],
    readingMinutes: 7,
    confidence: 0.63,
    signalDirection: "hold",
    horizon: "intraday",
    dataFreshness: "degraded",
  },
];
